### ISSUE TITLE
Is there a disarm command?

### ISSUE THREAD

**Issue by dpbacon** [vadim-bach/EyezOn-SmartThings-Switch#7]
I created an "armed-away" switch per your instructions using the envisalink EVL3 connected to a Honeywell panel. When Smartthings registered that a magnetic lock was activated then Smartthings sent the "on" command to the "armed-away" switch.   That worked fine and the system arms.  My problem is when the opposite occurs and the magnetic lock is unlocked I want the security system to disarm.  I assumed I could turn "off" the armed-away switch but that is not doing the trick.  Is there a specific "disarm" command I need to use?  BTW thanks for your work on this.

**Comment by vadim-bach** [comment]
The disarm should work just the same way. If you set the switch to off it should trigger a disarm to EyezOn. Are you doing this programatically (i.e. via routine) or using the UI? Also please double check your settings, in particular the disarm code, as I suspect that might be what's causing the issue if your arm is working fine.

**Comment by dpbacon** [comment]
As far as programmatically goes, here is the logic.  The magnetic lock is disarmed via a keypad.  A WiFi signal is sent to TUYA app which updates the SmartThings device.  I have verified that the SmartThings "MagLock" device event is fired changing it from off to on.  I have an automation defined within SmartThings that when MagLock turns on then the "Eyez-On Away" switch is to turn off.  That does not happen.  When you say to check the settings of the "disarm code" I don't know where I would do that.  When I create the switch in SmartThings there is not a UI interface asking what the disarm code is.

**Comment by vadim-bach** [comment]
I was referring to the "Disarm PIN" option. This would be configured in the same place as all the other options you must've gone through when you setup the switches (e.g. account ID, device ID, etc.). If you're not sure please take a look at the setup instructions again: https://github.com/vadim-bach/EyezOn-SmartThings-Switch/blob/master/README.md.

I recommend you first try to get the EyezOn switch working on its own by directly toggling it on and off. And then when you got that working you can integrate it with your MagLock logic. That way you can isolate where the issue is taking place.

**Comment by dpbacon** [comment]
I deleted and recreated the "Eyez-On Away" devices within SmartThings.  I
cannot get it to turn off. Whenever I click on it, the icon briefly flashes
to off but then goes right back to "On"

Dan Bacon

**Comment by vadim-bach** [comment]
I'm assuming you were able to configure the Disarm PIN correctly then?
Only thing I can think of is o check the SmartThings logs and see what's getting outputted for that EyezOn device handler. It's very odd that arm works but disarm doesn't.

**Comment by dpbacon** [comment]
Yes, the arm and disarm pins are the same.  I will check the logs tomorrow.
Thanks for your quick response.

Sent using fat fingers on tiny keyboard, Dan Bacon

**Comment by dpbacon** [comment]
Here are the pertinent logs.
8b8541ab-49ab-4a92-9414-0ffcc34ae5bc
<https://graph-na02-useast1.api.smartthings.com/ide/logs#8b8541ab-49ab-4a92-9414-0ffcc34ae5bc>
 4:45:07 AM: info Determined system status to be Away Armed at 04-27-22
4:45 AM
8b8541ab-49ab-4a92-9414-0ffcc34ae5bc
<https://graph-na02-useast1.api.smartthings.com/ide/logs#8b8541ab-49ab-4a92-9414-0ffcc34ae5bc>
 4:45:01 AM: info Operation disarm successfully submitted, now waiting for
system exit/disarm delay (5 sec) for confirmation...
8b8541ab-49ab-4a92-9414-0ffcc34ae5bc
<https://graph-na02-useast1.api.smartthings.com/ide/logs#8b8541ab-49ab-4a92-9414-0ffcc34ae5bc>
 4:45:01 AM: info Received request to perform operation: disarm
8b8541ab-49ab-4a92-9414-0ffcc34ae5bc
<https://graph-na02-useast1.api.smartthings.com/ide/logs#8b8541ab-49ab-4a92-9414-0ffcc34ae5bc>
 4:45:01 AM: info Determined system status to be Away Armed at 04-27-22
4:45 AM
8b8541ab-49ab-4a92-9414-0ffcc34ae5bc
<https://graph-na02-useast1.api.smartthings.com/ide/logs#8b8541ab-49ab-4a92-9414-0ffcc34ae5bc>
 4:45:01 AM: info Received request to disarm system. Mode: Away

I am unaware of a "5 sec exit/disarm delay setting" defined by our security
panel, but at 4:45:01 it's waiting.  But then at the six second mark it is
checking the status and finds it to be armed.

Neither EyezON or my security panel app show any disarming occurring at
that time.


Dan Bacon

**Comment by vadim-bach** [comment]
So actually that 5 second delay that you're seeing is a setting in this SmartThings Switch. The issue is that the EyezOn interface doesn't support any status subscriptions/push notifications so the only way to know when the system has flipped status is to poll for it explicitly. In order to not hammer the EyezOn server I'm basically using a preset delay to tell the switch how long the system takes to get armed/disarmed so it knows when to make the call to EyezOn to refresh the status. It's not a great solution by any means but does the trick for time being.

Having said that it's only really relevant mostly for arming, since the disarm should happen instanteneously so waiting 5 seconds before refreshing the status should be more than sufficient. Looking at the logs it seems like the disarm request went out fine but unfortunately I cannot tell if it got executed correctly due to the crappy API implementation on EyezOn side that will always return a 200 success response even if there was later some issue on its end.

I'm assuming you're able to disarm the system without issues manually through EyezOn panel page?

**Comment by dpbacon** [comment]
Sorry, I didn't get back here to close this issue before now.  All is working fine.

**Comment by dpbacon** [comment]
Yes I can disarm through the EyezOn app and portal.

Dan Bacon
